logging:
  level:
    org:
      springframework: DEBUG
      hibernate: DEBUG
spring:
  profiles:
    active: dev
  h2:
    console:
      enabled: true
#      path: /h2
      settings:
        trace: true
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect