DROP TABLE IF EXISTS Movies;

CREATE TABLE Movies (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  title VARCHAR(256) NOT NULL,
  date_released DATE NULL,
  director VARCHAR(256) NULL,

);

INSERT INTO Movies (title)
VALUES ('Bones', '2001-10-24')